[package]
name = "femto-riscv-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
panic = "abort"
codegen-units = 1
debug = 0
lto = true
opt-level = "z"
